add_newline = true
command_timeout = 1000

format = """
$directory\
$git_branch\
$git_status\
$python\
$nodejs\
$rust\
$golang\
$docker_context\
$kubernetes\
$cmd_duration\
$line_break\
$character"""

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"

[directory]
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "

[git_status]
format = '([$all_status$ahead_behind]($style) )'

[cmd_duration]
min_time = 2000
format = "[$duration]($style) "

[docker_context]
format = "[$symbol$context]($style) "
detect_files = ["docker-compose.yml", "Dockerfile"]

[kubernetes]
disabled = false
format = "[$symbol$context( \\($namespace\\))]($style) "

[python]
format = "[$symbol$version]($style) "

[nodejs]
format = "[$symbol$version]($style) "

[rust]
format = "[$symbol$version]($style) "

[golang]
format = "[$symbol$version]($style) "
