gui:
  showIcons: true
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - green
      - bold
git:
  paging:
    colorArg: always
    pager: delta --paging=never
  autoFetch: true
  autoRefresh: true
os:
  editPreset: "nvim"
