[manager]
show_hidden = true
sort_by = "natural"
sort_dir_first = true
linemode = "size"
ratio = [1, 4, 3]

[preview]
max_width = 1000
max_height = 1000
cache_dir = ""
image_quality = 75
tab_size = 2

[opener]
edit = [
  { run = '${EDITOR:-nvim} "$@"', block = true, for = "unix" },
]
open = [
  { run = 'xdg-open "$1"', desc = "Open", for = "linux" },
  { run = 'open "$@"', desc = "Open", for = "macos" },
]

[open]
rules = [
  { mime = "text/*", use = "edit" },
  { mime = "image/*", use = "open" },
  { mime = "video/*", use = "open" },
  { mime = "audio/*", use = "open" },
  { mime = "application/json", use = "edit" },
  { mime = "*/xml", use = "edit" },
  { mime = "*", use = "open" },
]
